{
  description = "Virtual HID telephony headset for Zoom and Google Meet";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
    flake-parts.url = "github:hercules-ci/flake-parts";
    systems.url = "github:nix-systems/default-linux";
    treefmt-nix.url = "github:numtide/treefmt-nix";
    treefmt-nix.inputs.nixpkgs.follows = "nixpkgs";
    crane.url = "github:ipetkov/crane";
    nuenv.url = "github:xav-ie/nuenv";
    nuenv.inputs.nixpkgs.follows = "nixpkgs";
    home-manager.url = "github:nix-community/home-manager/release-26.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    ags.url = "github:aylur/ags";
    ags.inputs.nixpkgs.follows = "nixpkgs";
  };

  nixConfig = {
    extra-substituters = [
      "https://nix-community.cachix.org"
    ];
    extra-trusted-public-keys = [
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems = import inputs.systems;

      imports = [
        inputs.treefmt-nix.flakeModule
      ];

      perSystem =
        {
          config,
          lib,
          pkgs,
          system,
          ...
        }:
        let
          craneLib = inputs.crane.mkLib pkgs;
        in
        {
          packages =
            (import ./packages {
              inherit pkgs craneLib;
              nuenv = inputs.nuenv.lib;
              agsPackages = inputs.ags.packages.${system};
            })
            // {
              default = config.packages.virtual-headset;
            };

          devShells.default =
            let
              devPkgs = with pkgs; [
                hid-tools
                pkg-config
                udev.dev
                libclang
                llvmPackages.clang
                linuxHeaders
                glibc.dev
              ];
              inherit (pkgs.stdenv) isDarwin isLinux;
            in
            pkgs.mkShell {
              packages =
                lib.optionals isLinux devPkgs
                ++ lib.optionals isDarwin (
                  with pkgs;
                  [
                    llvmPackages.libcxxStdenv
                    llvmPackages.libcxxClang
                  ]
                )
                ++ [ config.treefmt.build.wrapper ]
                ++ (with pkgs; [
                  cargo
                  rustc
                  rust-analyzer
                  clippy
                  rustfmt
                ]);

              shellHook =
                (lib.optionalString isLinux ''
                  export PKG_CONFIG_PATH="${
                    lib.concatMapStringsSep ":" (pkg: "${lib.getDev pkg}/lib/pkgconfig") devPkgs
                  }"
                  export LIBCLANG_PATH="${pkgs.libclang.lib}/lib"
                  export BINDGEN_EXTRA_CLANG_ARGS="-I${pkgs.linuxHeaders}/include -I${pkgs.glibc.dev}/include"
                '')
                + ''
                  printf "\n🎧 Virtual Headset development environment"
                  printf "\n📦 Use \e[32mcargo build\e[0m to build the project."
                  printf "\n💄 Use \e[32mtreefmt\e[0m to format the files."
                '';
            };

          treefmt = {
            projectRootFile = "flake.nix";
            programs = {
              nixfmt.enable = true;
              rustfmt.enable = true;
              just.enable = true;
              taplo.enable = true;
              prettier.enable = true;
            };
            settings.global.excludes = [
              "*.lock"
              # Generated by changesets; its formatting isn't prettier-clean and
              # regenerates on every release, so exclude it from the fmt check.
              "CHANGELOG.md"
              "**/CHANGELOG.md"
            ];
          };

          checks = {
            # Ensure all packages build successfully
            all-packages = pkgs.symlinkJoin {
              name = "virtual-headset-all";
              paths = builtins.attrValues (
                import ./packages {
                  inherit pkgs craneLib;
                  nuenv = inputs.nuenv.lib;
                  agsPackages = inputs.ags.packages.${system};
                }
              );
            };

            # Module wiring (udev, input group, Waybar, Firefox host). The VM
            # test definition + its script live in ./tests/nixos.
            modules = import ./tests/nixos/modules.nix { inherit pkgs inputs system; };

            # Runtime behaviour in a booted VM (starts muted, toggle, sources).
            # Definition + script live in ./tests/nixos.
            runtime = import ./tests/nixos/runtime.nix { inherit pkgs inputs system; };

            # Browser-extension install end to end: native-host registration,
            # id match, and driving the bridge as Firefox would.
            extension = import ./tests/nixos/extension.nix { inherit pkgs inputs system; };
          }
          # TypeScript unit tests (extension adapters/reconciler + panel logic).
          // (import ./tests/js-tests.nix { inherit pkgs; });
        };

      flake = {
        nixosModules.default =
          { pkgs, ... }:
          {
            _module.args.self = inputs.self;
            imports = [ ./nixosModules/default.nix ];
          };

        # Pass `self` by closure rather than `_module.args.self` so importing
        # several of these modules together doesn't collide on that arg.
        homeManagerModules.default =
          {
            config,
            lib,
            pkgs,
            ...
          }@args:
          import ./homeManagerModules/default.nix (args // { self = inputs.self; });

        homeManagerModules.firefox =
          {
            config,
            lib,
            pkgs,
            ...
          }@args:
          import ./homeManagerModules/firefox.nix (args // { self = inputs.self; });
      };
    };
}
